from competition.competition_main import Competition
from competition.league import League
from competition.fast_battle import SingleFastBattle
from competition.fast_teams_battle import TeamsFastBattle